id: P000452
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-16 15:40:41.228713
source_metadata:
  id: bdr:W00KG02677
  title: ཡིད་བཞིན་མཛོད་ཀྱི་འགྲེལ་པ་པདྨ་དཀར་པོ
  author: ''
  volumes:
    14f4ddc8064a459387cabb182b0e9fbb:
      image_group_id: I00KG02990
      title: Volume 1 of yid bzhin mdzod kyi 'grel pa
      volume_number: 1
      total_pages: 570
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
